name: Build ROMatis
on:
  push:
    branches: [ main ]
    paths:
      - "profiles/ROMatis.base.json"
      - "notams/*.txt"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
        
      - name: Inject NOTAM tokens
        shell: bash
        run: |
            set -euo pipefail
            SRC=profiles/ROMatis.base.json
            OUT=profiles/ROMatis.json
            cp "$SRC" "$OUT"

            for f in notams/*.txt; do
                ICAO_RAW=$(basename "$f" .txt)
                ICAO=$(echo "$ICAO_RAW" | tr '[:lower:]' '[:upper:]')
                VAL=$(perl -0777 -pe 's/([\/&\\"])/\\$1/g; s/\R/\\n/g' "$f")

                if grep -q "%%${ICAO}_NOTAMS%%" "$OUT"; then
                    sed -i "s/%%${ICAO}_NOTAMS%%/${VAL}/g" "$OUT"
                    echo "Injected NOTAMs for ${ICAO}"
                else
                    echo "::warning::Token %%${ICAO}_NOTAMS%% not found in ${OUT}"
                fi
            done

      - name: Bump updateSerial
        shell: bash
        run: |
          set -euo pipefail
          OUT=profiles/ROMatis.json
          TODAY=$(date -u +%Y%m%d)
          OLD=$(jq -r '(.updateSerial|tostring)? // "0"' "$OUT")
          echo "Current updateSerial: $OLD"

          OLD_DATE=${OLD:0:8}
          OLD_CTR=${OLD:8:2}

          if [[ "$OLD_DATE" == "$TODAY" && "$OLD_CTR" =~ ^[0-9][0-9]$ ]]; then
            CTR=$(printf "%02d" $((10#$OLD_CTR + 1)))
          else
            CTR="01"
          fi

          NEW="${TODAY}${CTR}"
          echo "Next updateSerial:   $NEW"
          TMP=$(mktemp)
          jq --arg v "$NEW" '.updateSerial = $v' "$OUT" > "$TMP" && mv "$TMP" "$OUT"
          jq -r '.updateSerial' "$OUT"

      - name: Commit build
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            UPDATE_SERIAL=$(jq -r '.updateSerial' profiles/ROMatis.json)
            git config user.name "github-actions"
            git config user.email "actions@users.noreply.github.com"
            git add profiles/ROMatis.json
            git commit -m "build: ROMatis with NOTAMs ${UPDATE_SERIAL}"
            git push
          fi
